[project]
name = "tic-tac-toe-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=1.17.1",
    "ruff>=0.12.8",
]
